name: io_extended
description: ODW input/output (files, network, etc.) package
version: 0.7.6
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/io

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: any
  path: any
  core:
    path: ../core
    version: ^0.7.6
  converter:
    path: ../converter
    version: ^0.7.6


dev_dependencies:
  benchmark_harness: any
  grinder: ^0.8.0
  test:  any
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.5
  yaml: ^2.1.12



