name: io
description: ODW input/output (files, network, etc.) package
version: 0.7.0
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/io

environment:
  sdk: '>=1.24.2 <2.1.0'

dependencies:
  args: any
  path: any
  core:
    path: C:/odw/sdk/core
    version: ^0.7.2
  convert:
    path: C:/odw/sdk/convert
    version: ^0.7.0


dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0+2
  test:  ^0.12.24
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.0
  yaml: ^2.1.12



