name: io
description: A starting point for Dart libraries or applications.
version: 0.1.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/io

environment:
  sdk: ^1.0.0

dependencies:
  args: any
  encode:
    path: C:/odw/sdk/convert
    version: 0.3.4
  core:
    path: C:/odw/sdk/core
    version: 0.4.1
  dictionary:
    path: C:/odw/sdk/dictionary
    version: 0.4.1
  path: any

dev_dependencies:
  benchmark_harness: any
  grinder: any
  test: ^0.12.0


