name: io
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>
homepage: https://opendicomweb.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  bytebuf:
    path: C:/odw/sdk/bytebuf
  convert:
    path: C:/odw/sdk/convert
  core:
    path: C:/odw/sdk/core
  uuid:
    path: C:/odw/sdk/uuid
  path: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
