name: io
description: A starting point for Dart libraries or applications.
version: 0.1.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>
homepage: https://opendicomweb.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: any
  bytebuf:
    path: C:/odw/sdk/bytebuf
  encode:
    path: C:/odw/sdk/encode
  core:
    path: C:/odw/sdk/core
  path: any
  uuid:
    path: C:/odw/sdk/uuid
  path: any

dev_dependencies:
  grinder: any
  test: '>=0.12.0 <0.13.0'


