name: io
description: The Open DICOMweb SDK I/O Library
version: 0.2.0
author: Jim Philbin <mailto:jfphilbin@gmail.com>
homepage: https://opendicomweb.github.io

environment:
  sdk: ^1.0.0

dependencies:
  args: any
  encode:
    path: C:/odw/sdk/convert
    version: 0.3.3
  core:
    path: C:/odw/sdk/core
    version: 0.4.1
  dictionary:
    path: C:/odw/sdk/dictionary
    version: 0.4.1
  path: any

dev_dependencies:
  benchmark_harness: any
  test: ^0.12.0
  grinder: any

