name: io
description: A starting point for Dart libraries or applications.
version: 0.5.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/io

environment:
  sdk: ^1.21.0

dependencies:
  args: any
  path: any
  common:
    git:
      url: https://github.com/OpenDICOMweb/common
      ref: develop
      version: ^0.5.2
   #   path: C:/odw/sdk/common
   #   version: ^0.5.2
  core:
    git:
      url: https://github.com/OpenDICOMweb/core
      ref: develop
      version: ^0.5.1
    #  path: C:/odw/sdk/core
    #  version: ^0.5.1
  convertX:
    git:
      url: https://github.com/OpenDICOMweb/convert
      ref: develop
      version: ^0.5.0
  #  path: C:/odw/sdk/core
  #  version: ^0.5.1

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test:  ^0.12.0



