name: io
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Jim Philbin <mailto:jfphilbin@gmail.com>
homepage: https://opendicomweb.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  odwsdk:
    path: C:/odw/sdk/odwsdk
  #date_time:
  #  path: C:/odw/sdk/utils/date_time
  uuid:
    path: C:/odw/sdk/uuid
  path: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
