name: io
description: Open DICOMweb SDK Input/Output Packages.
version: 0.5.4
author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/io

environment:
  sdk: ^1.22.0

dependencies:
  args: any
  path: any
  common:
  #  git:
  #    url: https://github.com/OpenDICOMweb/common.git
  #    ref: develop
    path: C:/odw/sdk/common
    version: ^0.5.4
  core:
  #  git:
  #    url: https://github.com/OpenDICOMweb/core.git
  #    ref: develop
    path: C:/odw/sdk/core
    version: ^0.5.4
  convertX:
  #  git:
  #    url: https://github.com/OpenDICOMweb/convert.git
  #    ref: develop
    path: C:/odw/sdk/convert
    version: ^0.5.4

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test:  ^0.12.0
  test_tools:
    path: C:/odw/sdk/test_tools
    version: ^0.5.4



